[workspace]
authors = ["QwertyVole <fakeqwertzy@gmail.com>"]
channels = ["conda-forge"]
name = "SEN0592"
platforms = ["linux-64"]
version = "0.1.0"


[tasks]
compile = "esphome compile firmware/atomlite-distance.yaml"
upload = "esphome upload firmware/atomlite-distance.yaml"
run = "esphome run firmware/atomlite-distance.yaml"
logs = "esphome logs firmware/atomlite-distance.yaml"
clean = "esphome clean firmware/atomlite-distance.yaml"

[dependencies]
python = ">=3.14.6,<3.15"

[pypi-dependencies]
esphome = ">=2026.7.3, <2027"
